#  (C) Crown Copyright, Met Office, 2023.
from pathlib import Path

import ennuf


class KGOProgramWriterTester:
    def __init__(self, model: ennuf.Model):
        self.model = model
        self._program_name = "test_kgo"
        self._nnmod = f"{model.name}_mod"
        self._nnsubroutine = model.name
        self._precision = "4"
        self._unitname = "unit"

    def write(self, file: Path | str) -> None:
        program = (
            f"{self._header()}\n"
            f"{self._program_begin_stmt()}\n"
            f"{self._imports()}\n"
            f"{self._implicitnone()}\n"
            f"{self._declarations()}\n"
            f"{self._body()}\n"
            f"{self._program_end_stmt()}\n"
        )
        mode = "w"
        if not isinstance(file, Path):
            file = Path(file)
        with open(file, mode) as module_file:
            module_file.write(program)

    def _header(self) -> str:
        return f'! file "{self._program_name}" autogenerated by ennuf test suite'

    def _program_begin_stmt(self) -> str:
        return f"PROGRAM {self._program_name}"

    def _program_end_stmt(self) -> str:
        return f"END PROGRAM {self._program_name}"

    def _imports(self) -> str:
        return f"USE {self._nnmod}, ONLY: {self._nnsubroutine}"

    @staticmethod
    def _implicitnone() -> str:
        return "IMPLICIT NONE"

    def _declarations(self) -> str:
        decls = f"INTEGER :: {self._unitname}\n"
        for layer in self.model.inputs:
            decl = layer.get_fortran_type_declaration(self._precision)
            decls = f"{decls}{decl}\n"
        for layer in self.model.outputs:
            decl = layer.get_fortran_type_declaration(self._precision)
            decls = f"{decls}{decl}\n"
        return decls

    def _body(self) -> str:
        body = ""
        arglist = ""
        for layer in self.model.inputs:
            arglist += f"{layer.name}, "
            body += f"{self._read_input(layer.name)}\n"
        for layer in self.model.outputs:
            arglist += f"{layer.output_name}, "
        body += f"CALL {self._nnsubroutine}({arglist[:-2]})\n\n"
        for layer in self.model.outputs:
            body += f"{self._write_output(layer.name, layer.output_name)}\n"
        return body

    def _read_input(self, layername) -> str:
        return (
            f'OPEN({self._unitname}, FILE="in_{layername}.dat",'
            'FORM="UNFORMATTED", STATUS="UNKNOWN", ACTION="READ", ACCESS="STREAM")\n'
            f"READ({self._unitname}) {layername}\n"
            f"CLOSE({self._unitname})\n"
        )

    def _write_output(self, layername, layeroutputname) -> str:
        return (
            f'OPEN({self._unitname}, FILE="out_{layername}.dat",'
            'FORM="UNFORMATTED", STATUS="REPLACE", ACTION="WRITE", ACCESS="STREAM")\n'
            f"WRITE({self._unitname}) {layeroutputname}\n"
            f"CLOSE({self._unitname})\n"
        )
